import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const money = (value) => `PKR ${Number(value).toLocaleString()}`;

// Builds a clean client-side PDF from the saved invoice data.
export const downloadInvoicePdf = (invoice) => {
  const doc = new jsPDF();
  const customer = invoice.customer || {};

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 42, "F");
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(16, 11, 14, 14, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.text("CF", 19, 20);
  doc.setFontSize(17);
  doc.text("ClientFlow CRM", 35, 18);
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text("Customer Management Suite", 35, 25);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("INVOICE", 194, 17, { align: "right" });
  doc.setFontSize(9);
  doc.text(invoice.invoiceNumber, 194, 24, { align: "right" });
  doc.text(new Date(invoice.invoiceDate).toLocaleDateString(), 194, 30, { align: "right" });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text("BILL TO", 16, 56);
  doc.setFontSize(14);
  doc.text(customer.name || "Customer", 16, 65);
  doc.setFontSize(10);
  doc.text(customer.company || "", 16, 72);
  doc.text(customer.email || "", 16, 78);
  doc.text(customer.phone || "", 16, 84);

  autoTable(doc, {
    startY: 96,
    head: [["Service", "Qty", "Price", "Amount"]],
    body: invoice.services.map((item) => [
      item.description,
      item.quantity,
      money(item.price),
      money(item.amount),
    ]),
    headStyles: { fillColor: [37, 99, 235] },
    styles: { cellPadding: 4 },
  });

  const finalY = doc.lastAutoTable.finalY + 12;
  doc.setFontSize(14);
  doc.text(`Total: ${money(invoice.totalAmount)}`, 194, finalY, { align: "right" });
  doc.setFontSize(10);
  doc.text("Summary", 16, finalY + 15);
  doc.text(invoice.summary || "Thank you for your business.", 16, finalY + 23, { maxWidth: 178 });
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by ClientFlow CRM - Final Term Project", 105, 286, { align: "center" });
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
};
