import { Download } from "lucide-react";
import { downloadInvoicePdf } from "@/lib/pdf";
import BrandLogo from "./BrandLogo";

const money = (value) => `PKR ${Number(value || 0).toLocaleString()}`;

export default function InvoicePreview({ invoice, showDownload = true }) {
  if (!invoice) {
    return <div className="invoice-placeholder"><span>INV</span><h3>Invoice preview</h3><p>Select a customer and add services to preview your invoice.</p></div>;
  }

  return (
    <article className="invoice-paper">
      <header><BrandLogo size="sm" /><div><h2>INVOICE</h2><span>{invoice.invoiceNumber || "Draft invoice"}</span></div></header>
      <div className="invoice-meta"><div><small>BILL TO</small><strong>{invoice.customer?.name || "Select customer"}</strong><span>{invoice.customer?.company}</span><span>{invoice.customer?.email}</span><span>{invoice.customer?.phone}</span></div><div><small>INVOICE DATE</small><strong>{invoice.invoiceDate ? new Date(invoice.invoiceDate).toLocaleDateString() : "Today"}</strong></div></div>
      <div className="invoice-service-table"><div className="invoice-service-head"><span>Service</span><span>Qty</span><span>Price</span><span>Amount</span></div>{invoice.services.map((item, index) => <div className="invoice-service-row" key={index}><span>{item.description || "Service description"}</span><span>{item.quantity}</span><span>{money(item.price)}</span><span>{money(item.amount ?? item.quantity * item.price)}</span></div>)}</div>
      <div className="invoice-total"><span>Total amount</span><strong>{money(invoice.totalAmount)}</strong></div>
      <div className="invoice-summary"><small>SUMMARY</small><p>{invoice.summary || "Thank you for your business."}</p></div>
      <footer>Generated by ClientFlow CRM - Final Term Project</footer>
      {showDownload && invoice._id && <button className="button primary invoice-download" onClick={() => downloadInvoicePdf(invoice)}><Download size={17} /> Download PDF</button>}
    </article>
  );
}
